services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  Presta_Shop\Module\Link_List\Controller\Admin\Improve\Design\Link_Block_Controller: ~

  # Link block form handler
  prestashop.module.link_block.form_handler:
    class: 'Presta_Shop\Presta_Shop\Core\Form\Form_Handler'
    arguments:
      $formBuilder: '@=service("form.factory").createBuilder()'
      $hookDispatcher: '@prestashop.core.hook.dispatcher'
      $formDataProvider: '@Presta_Shop\Module\Link_List\Form\Link_Block_Form_Data_Provider'
      $formTypes:
        'link_block': 'Presta_Shop\Module\Link_List\Form\Type\Link_Block_Type'
      $hookName: 'AdminLinkWidget'

  # Link block form data provider
  Presta_Shop\Module\Link_List\Form\Link_Block_Form_Data_Provider:
    arguments:
      $repository: '@Presta_Shop\Module\Link_List\Repository\Link_Block_Repository'
      $cache: '@Presta_Shop\Module\Link_List\Cache\Legacy_Link_Block_Cache'
      $languages: '@=service("prestashop.adapter.legacy.context").getLanguages(false, service("prestashop.adapter.shop.context").getContextShopID())'
      $shopContext: '@prestashop.adapter.shop.context'
      $configuration: '@prestashop.adapter.legacy.configuration'

  Presta_Shop\Module\Link_List\Cache\Legacy_Link_Block_Cache: ~

  # Form types
  Presta_Shop\Module\Link_List\Form\Type\Link_Block_Type:
    parent: 'form.type.translatable.aware'
    arguments:
      $hookChoices: '@=service("prestashop.module.link_block.choice_provider.hook").getChoices()'
      $cmsPageChoices: '@=service("prestashop.module.link_block.choice_provider.cms_page").getChoices()'
      $productPageChoices: '@=service("prestashop.module.link_block.choice_provider.product_page").getChoices()'
      $staticPageChoices: '@=service("prestashop.module.link_block.choice_provider.static_page").getChoices()'
      $categoryChoices: '@=service("prestashop.module.link_block.choice_provider.category").getChoices()'
      $isMultiStoreUsed: '@=service("prestashop.adapter.feature.multistore").isUsed()'
    tags:
      - { name: form.type }

  Presta_Shop\Module\Link_List\Form\Type\Custom_Url_Type:
    parent: 'form.type.translatable.aware'
    tags:
      - { name: form.type }

  Presta_Shop\Module\Link_List\Form\Type\Translate_Custom_Url_Type:
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - "@=service('prestashop.adapter.legacy.context').getAvailableLanguages()"
      - '@router.default'
      - "@=service('prestashop.adapter.legacy.configuration').getBoolean('PS_BO_ALLOW_EMPLOYEE_FORM_LANG')"
      - "@=service('prestashop.adapter.legacy.context').getContext().cookie.employee_form_lang"
      - "@=service('prestashop.adapter.legacy.configuration').getInt('PS_LANG_DEFAULT')"
    tags:
      - { name: form.type }

  # Grid data query builder
  prestashop.module.link_block.grid.query_builder:
    class: Presta_Shop\Module\Link_List\Core\Grid\Query\Link_Block_Query_Builder
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  # Grid Data Factory
  prestashop.module.link_block.grid.data_factory:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      $gridQueryBuilder: '@prestashop.module.link_block.grid.query_builder'
      $hookDispatcher: '@prestashop.core.hook.dispatcher'
      $queryParser: '@prestashop.core.grid.query.doctrine_query_parser'
      $gridId: 'link_block'

  # Link block grid Factory
  Presta_Shop\Module\Link_List\Core\Grid\Link_Block_Grid_Factory:
    arguments:
      $translator: '@translator'
      $hookDispatcher: '@prestashop.core.hook.dispatcher'
      $dataFactory: '@prestashop.module.link_block.grid.data_factory'
      $filterFormFactory: '@prestashop.core.grid.filter.form_factory'
      $shopContext: '@prestashop.adapter.shop.context'

  # Form choices providers
  prestashop.module.link_block.choice_provider.hook:
    class: Presta_Shop\Module\Link_List\Form\Choice_Provider\Hook_Choice_Provider
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  prestashop.module.link_block.choice_provider.cms_category:
    class: Presta_Shop\Module\Link_List\Form\Choice_Provider\CMS_Category_Choice_Provider
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $idLang: '@=service("prestashop.adapter.legacy.context").getLanguage().id'
      $shopIds: '@=service("prestashop.adapter.shop.context").getContextListShopID()'

  prestashop.module.link_block.choice_provider.category:
    class: Presta_Shop\Module\Link_List\Form\Choice_Provider\Category_Choice_Provider
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $idLang: '@=service("prestashop.adapter.legacy.context").getLanguage().id'
      $shopIds: '@=service("prestashop.adapter.shop.context").getContextListShopID()'

  prestashop.module.link_block.choice_provider.cms_page:
    class: Presta_Shop\Module\Link_List\Form\Choice_Provider\CMS_Page_Choice_Provider
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $categories: '@=service("prestashop.module.link_block.choice_provider.cms_category").getChoices()'
      $idLang: '@=service("prestashop.adapter.legacy.context").getLanguage().id'
      $shopIds: '@=service("prestashop.adapter.shop.context").getContextListShopID()'

  prestashop.module.link_block.choice_provider.product_page:
    class: Presta_Shop\Module\Link_List\Form\Choice_Provider\Page_Choice_Provider
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $idLang: '@=service("prestashop.adapter.legacy.context").getLanguage().id'
      $shopIds: '@=service("prestashop.adapter.shop.context").getContextListShopID()'
      $pageNames:
        - 'prices-drop'
        - 'new-products'
        - 'best-sales'

  prestashop.module.link_block.choice_provider.static_page:
    class: Presta_Shop\Module\Link_List\Form\Choice_Provider\Page_Choice_Provider
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $idLang: '@=service("prestashop.adapter.legacy.context").getLanguage().id'
      $shopIds: '@=service("prestashop.adapter.shop.context").getContextListShopID()'
      $pageNames:
        - 'contact'
        - 'sitemap'
        - 'stores'
        - 'authentication'
        - 'registration'
        - 'my-account'
