services:
  _defaults:
    public: true

  Presta_Shop\Module\Link_List\Repository\Link_Block_Repository:
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $languages: '@=service("prestashop.adapter.legacy.context").getLanguages(false, service("prestashop.adapter.shop.context").getContextShopID())'
      $translator: '@translator'
      $isMultiStoreUsed: '@=service("prestashop.adapter.feature.multistore").isUsed()'
      $multiStoreContext: '@prestashop.adapter.shop.context'
      $objectModelHandler: '@prestashop.module.link_block.adapter.object_model_handler'

  prestashop.module.link_block.repository:
    alias: Presta_Shop\Module\Link_List\Repository\Link_Block_Repository

  prestashop.module.link_block.adapter.object_model_handler:
    class: 'Presta_Shop\Module\Link_List\Adapter\Object_Model_Handler'
